### ISSUE TITLE
These are static fields ?

### ISSUE THREAD

**Issue by muhammad-ishfaq-com** [muhammad-ishfaq-com/flyhangar7#6]
https://www.flyhangar7.com/-temporary-slug-a4fea31d-fc7e-4f30-818e-0065087fb4eb?hs_preview=oPwTKLCj-27895960758

https://prnt.sc/ru0kox

**Comment by computangit** [comment]
These contact form was sent by the client so I just used the form and these are drop-down options

**Comment by muhammad-ishfaq-com** [comment]
Closed
